# Generated by Django 5.2.3 on 2025-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Income', 'income'), ('Expense', 'expense')], max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('total_expense', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('total_transactions', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
