# Generated by Django 5.2.3 on 2025-07-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_transactions',
            new_name='total_balance',
        ),
    ]
